# Create folder instead of file, because secrets contain the file name
# and we don't want a random one
- tempfile:
    state: directory
  register: secret_path

- copy:
    content: "{{kubectl_content}}"
    dest: "{{secret_path.path}}/{{kubectl_secret_name}}.yml"

- name: create temporary file
  tempfile:
    state: file
    suffix: .config
  register: kubeconfig_path

- copy:
    src: "{{env}}.kubeconfig"
    dest: "{{kubeconfig_path.path}}"

- command: kubectl get secrets {{kubectl_secret_name}} --kubeconfig={{kubeconfig_path.path}}
  register: get_secret_result
  failed_when: False

- command: kubectl create secret generic {{kubectl_secret_name}} --from-file="{{secret_path.path}}/{{kubectl_secret_name}}.yml" --kubeconfig={{kubeconfig_path.path}}
  when: get_secret_result.rc != 0
